
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueWs", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWs {


    /**
     * 
     * @param mantant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertionFromEuroToDH")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertionFromEuroToDH", targetNamespace = "http://WebService/", className = "proxy.ConvertionFromEuroToDH")
    @ResponseWrapper(localName = "ConvertionFromEuroToDHResponse", targetNamespace = "http://WebService/", className = "proxy.ConvertionFromEuroToDHResponse")
    @Action(input = "http://WebService/BanqueWs/ConvertionFromEuroToDHRequest", output = "http://WebService/BanqueWs/ConvertionFromEuroToDHResponse")
    public double convertionFromEuroToDH(
        @WebParam(name = "mantant", targetNamespace = "")
        double mantant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WebService/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WebService/", className = "proxy.GetCompteResponse")
    @Action(input = "http://WebService/BanqueWs/getCompteRequest", output = "http://WebService/BanqueWs/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://WebService/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://WebService/", className = "proxy.ListComptesResponse")
    @Action(input = "http://WebService/BanqueWs/listComptesRequest", output = "http://WebService/BanqueWs/listComptesResponse")
    public List<Compte> listComptes();

}
